### ISSUE TITLE
Eliminate deprecated REST interfaces, streamline interface

### ISSUE THREAD

**Issue by behas** [graphsense/graphsense-REST#10]

**Comment by bartham** [comment]
Done!

**Comment by behas** [comment]
@myrho are all these interfaces still needed:

/login
/token_refresh
/logout_access

/stats
/<currency>/exchangerates

/<currency>/block/<int:height>
/<currency>/blocks
/<currency>/block/<int:height>/transactions
/<currency>/block/<int:height>/transactions.csv

/<currency>/tx/<txHash>

/<currency>/transactions

/<currency>/search
/labelsearch

/<currency>/address/<address>
/<currency>/address/<address>/tags
/<currency>/address/<address>/tags.csv

/<currency>/address_with_tags/<address>

/<currency>/address/<address>/transactions

/<currency>/address/<address>/implicitTags


/<currency>/address/<address>/cluster
/<currency>/address/<address>/cluster_with_tags

/<currency>/address/<address>/neighbors
/<currency>/address/<address>/neighbors.csv

/<currency>/cluster/<cluster>
/<currency>/cluster_with_tags/<cluster>
/<currency>/cluster/<cluster>/tags
/<currency>/cluster/<cluster>/tags.csv

/<currency>/cluster/<cluster>/addresses

/<currency>/cluster/<cluster>/neighbors
/<currency>/cluster/<cluster>/neighbors.csv

/label/<label>
/label/<label>/tags

/<currency>/cluster/<cluster>/search

**Comment by myrho** [comment]
The dashboard does not use:

* exchangerates
* implicitTags

**Comment by behas** [comment]
Done. Fully rewrote REST interface.
