### ISSUE TITLE
Unexpected empty ETH edge transactions table

### ISSUE THREAD

**Issue by myrho** [graphsense/graphsense-REST#102]
Check: `/graph/eth/addresslink/0x7be8076f4ea4a4ad08075c2508e481d6c946d12b/0/0x5445092634581774a680e4dedd4ec9bfc35a26fd/1?table=transactions`

**Comment by soad003** [comment]
Observation: if I increase the page size to 1000 I get results (1000 results) after waiting a long time. 

`https://api.ikna.io/eth/addresses/0x7be8076f4ea4a4ad08075c2508e481d6c946d12b/links?neighbor=0x5445092634581774a680e4dedd4ec9bfc35a26fd&pagesize=1000`

**Comment by myrho** [comment]
No longer empty, but still the number of tx on the edge does not match the number of returned tx on the edge.

**Comment by soad003** [comment]
@myrho currently we count NR of transactions that produced relations and not the number of relations. That's probably the reasons for the differences. I would suggest to close this issue and open another one in the gs-spark repo.
