### ISSUE TITLE
Summary statistics do not load automatically in dashboard

### ISSUE THREAD

**Issue by defconst** [graphsense/graphsense-REST#30]
When starting the graphsense-REST docker container summary statistics are not displayed immediately, they only appear after the first login of a registered user.

**Comment by behas** [comment]
@defconst is this still an issue?

**Comment by defconst** [comment]
yes

**Comment by defconst** [comment]
> @defconst is this still an issue?

yes

**Comment by behas** [comment]
@defconst @MatteoRomiti this should be solved now, right?

**Comment by behas** [comment]
rates are now loaded directly -> no loading delays -> issue closed
