### ISSUE TITLE
Design Python API +  Command line interface

### ISSUE THREAD

**Issue by behas** [graphsense/graphsense-REST#38]

**Comment by myrho** [comment]
OpenAPI spec is complete (see [this repo](/graphsense/graphsense-openapi)). 
Python client is generated [here](/graphsense/graphsense-python).

CLI work in progress.

**Comment by myrho** [comment]
Authorization with the CLI openapi generator works if I hardcode credentials although there should be a way to pass a credentials file at runtime. I haven't figured out yet how. I've asked for [help](https://github.com/danielgtaylor/openapi-cli-generator/issues/38) but haven't got an answer. 

The author seems to put more focus on the successor of the openapi-cli-generator: [restish](rest.sh). I've also tried this tool but it crashes when reading in the graphsense openapi spec ... 

I think I need more time for the graphsense CLI.
