### ISSUE TITLE
CSV generation functions

### ISSUE THREAD

**Issue by behas** [graphsense/graphsense-REST#4]
Provide functions supporting CSV download of tags and addresses.

Introduce max threshold

**Comment by myrho** [comment]
perhaps stream like http://flask.pocoo.org/docs/0.12/patterns/streaming/

**Comment by bartham** [comment]
Done!

**Comment by myrho** [comment]
Hm, these return just the first page of the cassandra table. I think streaming the pages one after the other to client would be a neat, memory-saving solution. Could it work as the described on the page I've posted above?

**Comment by bartham** [comment]
The implementation already uses streaming as you wished. I only streamed the current page as I was not sure if I should stream everything or not. What you can do is increase the page size to max int. That way you would get everything. Hope it works.

**Comment by myrho** [comment]
This results in a timeout of the cassandra query.
