### ISSUE TITLE
504 Gateway Timeout when retrieving relations from superclusters

### ISSUE THREAD

**Issue by behas** [graphsense/graphsense-REST#46]
Retrieving incoming/outgoing relations from a super-cluster (e.g., 259096273) returns a 504 error. The example cluster has more than 4M incoming and 2.5M outgoing relations. Maybe the query doesn't use any limits at the moment.

Reproducible example:

```
with graphsense.ApiClient(configuration) as api_client:
    api_instance = graphsense.EntitiesApi(api_client)
    currency = 'btc' # str | The cryptocurrency (e.g., btc)
    entity = 259096273

    try:
        # Get an address with tags
        api_response = api_instance.api_response = api_instance.list_entity_neighbors(
            currency, entity, 'in', pagesize=10)(currency, entity)
        pprint(api_response)
    except ApiException as e:
        print("Exception when calling EntitiesApi->get_entity: %s\n" % e)
```

**Comment by myrho** [comment]
Tried to reproduce on current develop branch with an LTC supercluster:
`/ltc/entities/57653204/neighbors?direction=in&pagesize=10`

Works though.

**Comment by myrho** [comment]
Tried with btc 96423525. Works also on develop.
