### ISSUE TITLE
Can not start REST interface. 

### ISSUE THREAD

**Issue by ridicoulous** [graphsense/graphsense-REST#5]
Hello. First of all, thank you for a great work!
I succesfully performed previous steps like parsing blockchain node through blocksci, imported  firs 10K blocks to Cassandra and processed it by SPARK. And have this exception on starting rest service:
```python3 graphsenserest.py
Loading exchange rates for btc ...
Failed to query exchange rates. Cause:
Error from server: code=2200 [Invalid query] message="LIMIT must be strictly positive"
``` 
Any ideas?

**Comment by defconst** [comment]
Maybe an empty or missing `exchange_rates` table?
