### ISSUE TITLE
REST Service Timeout

### ISSUE THREAD

**Issue by jjacks95** [graphsense/graphsense-REST#6]
After building the docker to run the REST API, which seemed to execute correctly without errors. I am unable to access the REST API, every time I try to access through localhost it times out.

Not sure what I could be missing will try changing the service off localhost.

As well, what is the `SECRET_KEY` referred to in the `config.json` file in the `app/` folder?

**Comment by defconst** [comment]
`SECRET_KEY` is the key of the [Flask session](http://flask.pocoo.org/docs/1.0/quickstart/#sessions).
