### ISSUE TITLE
Conflicting tags with equal confidence score

### ISSUE THREAD

**Issue by behas** [graphsense/graphsense-REST#75]
It can happen that an entity is associated with several conflicting attribution tags with equal confidence scores; in such cases we should implement a majority vote, e.g., if x tags says the label is A and more than x tags say the label is B, then label should be B.

Example entity (root address): 1JS1Z7jqn8veVvcEcYXTnfiexScqeYbRDr

**Comment by behas** [comment]
should work now

**Comment by behas** [comment]
This works now, but for some clusters, the tag defining an entity is not highlighted.

**Comment by myrho** [comment]
Fixed
